default_platform(:android)

platform :android do
  desc "Build and publish to Huawei AppGallery"
  lane :publish_huawei do
    gradle(task: "clean assembleHuaweiStore")
    output_path = "build/outputs/apk/huawei/store/"
    output_json_path = output_path + "output-metadata.json"
    build_output = load_json(json_path: output_json_path)
    elements = build_output["elements"][0]
    apk_path = output_path + elements["outputFile"]
    huawei_appgallery_connect(
      client_id: ENV["HUAWEI_CLIENT_ID"],
      client_secret: ENV["HUAWEI_CLIENT_SECRET"],
      app_id: ENV["HUAWEI_APP_ID"],
      apk_path: "#{apk_path}",
      submit_for_review: true
    )
  end
end