name: Android CI

on:
  pull_request:
  push:
    branches: [master]
concurrency:
  group: ${{ github.ref }}
  cancel-in-progress: true

jobs:
  check:
    runs-on: ubuntu-24.04
    steps:
    - uses: actions/checkout@v6
    - name: Set up JDK
      uses: actions/setup-java@v5
      with:
        distribution: 'temurin'
        java-version: '25'
    - name: Setup Android SDK
      uses: android-actions/setup-android@v3
    - name: Build
      run: ./gradlew assembleNext
